"""User changes

Revision ID: 15ec3dd4b493
Revises: 93ef6603f8de
Create Date: 2024-05-19 21:41:14.130639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15ec3dd4b493'
down_revision: Union[str, None] = '93ef6603f8de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activeUsers', sa.Column('state', sa.Integer(), nullable=True))
    op.add_column('activeUsers', sa.Column('mission', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activeUsers', 'mission')
    op.drop_column('activeUsers', 'state')
    # ### end Alembic commands ###
