"""App model

Revision ID: 5ddb728c66bc
Revises: 09452d64463b
Create Date: 2024-04-14 12:22:11.417515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ddb728c66bc'
down_revision: Union[str, None] = '09452d64463b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_key', sa.String(), nullable=True),
    sa.Column('secret', sa.String(), nullable=True),
    sa.Column('management_key', sa.String(), nullable=True),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('date_status', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('rooms', sa.Column('app_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rooms', 'apps', ['app_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'app_id')
    op.drop_table('apps')
    # ### end Alembic commands ###
