"""User changes new

Revision ID: efa749086bd7
Revises: 15ec3dd4b493
Create Date: 2024-05-19 22:32:39.201202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa749086bd7'
down_revision: Union[str, None] = '15ec3dd4b493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activeUsers', sa.Column('armed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activeUsers', 'armed')
    # ### end Alembic commands ###
