"""Change mermaid and order

Revision ID: fc92c82621fa
Revises: 31e7e6489010
Create Date: 2024-04-14 20:34:21.453279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc92c82621fa'
down_revision: Union[str, None] = '31e7e6489010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activeUsers', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('activeUsers', sa.Column('mermaid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activeUsers', 'mermaid')
    op.drop_column('activeUsers', 'order')
    # ### end Alembic commands ###
